version: 0.2

env:
  variables:
    APP_NAME: "verademo-go"
    ZIP_FILE: "verademo-go.zip"
    VERACODE_API_WRAPPER_JAR: "/opt/veracode/api-wrapper.jar"
  secrets-manager:
    VERACODE_API_ID: "veracode-secrets:VERACODE_API_ID"
    VERACODE_API_KEY: "veracode-secrets:VERACODE_API_KEY"
    SRCCLR_API_TOKEN: "veracode-secrets:SRCCLR_API_TOKEN"

phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto8
    commands:
      - echo "Installing Veracode CLI tools..."
      - curl -sSL https://download.sourceclear.com/ci.sh -o /usr/local/bin/ci.sh
      - chmod +x /usr/local/bin/ci.sh
      - echo "Install complete."

  pre_build:
    commands:
      - echo "Cleaning previous zip..."
      - rm -f $ZIP_FILE

  build:
    commands:
      - echo "Zipping app files..."
      - zip -r $ZIP_FILE .

      - echo "Uploading for static scan using Veracode API Wrapper..."
      - java -jar $VERACODE_API_WRAPPER_JAR \
          -vid $VERACODE_API_ID -vkey $VERACODE_API_KEY \
          -action UploadAndScan -appname "$APP_NAME" -createprofile true \
          -filepath $ZIP_FILE -version "CodeBuild-Run-$(date +%s)"

      - echo "Running SCA scan with SourceClear..."
      - export SRCCLR_API_TOKEN=$SRCCLR_API_TOKEN
      - ci.sh --no-issue-tracking --quick

      - echo "Running container scan..."
      - curl -sSLo container_scan https://downloads.veracode.com/securityscan/container_iac_secrets_scanning
      - chmod +x container_scan
      - ./container_scan \
          --vid $VERACODE_API_ID \
          --vkey $VERACODE_API_KEY \
          --command scan \
          --type directory \
          --source ./ \
          --format table

artifacts:
  files:
    - $ZIP_FILE
  name: scan-target
